apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: kdw-dash-lb
spec:
  type: LoadBalancer
  ports:
  - port: 443
    targetPort: 8443
  selector:
    k8s-app: kubernetes-dashboard
